services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.10.2
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/template:/usr/share/logstash/template:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./data:/usr/share/logstash/data
      - logstash-data:/usr/share/logstash/data/plugins
    ports:
      - "5000:5000"
      - "9600:9600"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.10.2
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
      - kibana-data:/usr/share/kibana/data
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  cerebro:
    image: yannart/cerebro
    ports:
      - "9000:9000"
    networks:
      - elastic
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
    driver: local
  logstash-data:
    driver: local

networks:
  elastic:
    driver: bridge
